version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
#  db:
#    image: postgres
#    volumes:
#      - 'pgdata:/var/lib/postgresql/data/'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangotest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
#      - db
      - elasticsearch

volumes:
  pgdata:
    driver: local
  esdata1:
    driver: local

networks:
  esnet: